version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        columns:
          - name: date_date
            description: purchase date
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foregn key to product
          - name: revenue
            description: the amount paid by the customer to purchase a product
          - name: quantity
            description: quantity of products purchassed for this order 
        tests:
          - unique:
              column_name: "(orders_id ||'-'|| pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: prodducts_id
            description: primary key of product table
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchase price of a product
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez
        columns:
          - name: orders_id
            description: primary key of ship table
            tests:
              - unique
              - not_null    
          - name: shipping_fee
            description: the price that the customer pays for shipping
          - name: log_cost
            description: the cost of preparing the parcel in warehouse
          - name: ship_cost
            description: shipping cost paid by greenweez to the carrier/transporter
